name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5 # or alternative dependency management

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
